# Generated by Django 4.2.16 on 2024-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_id', models.IntegerField()),
                ('attacking_player_name', models.CharField(max_length=30)),
                ('attacking_village_name', models.CharField(max_length=30)),
                ('attacking_village_coords_x', models.IntegerField()),
                ('attacking_village_coords_y', models.IntegerField()),
                ('defending_player_name', models.CharField(max_length=30)),
                ('defending_village_name', models.CharField(max_length=30)),
                ('defending_village_coords_x', models.IntegerField()),
                ('defending_village_coords_y', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('submitter_notes', models.CharField(max_length=100)),
                ('admin_notes', models.CharField(max_length=200)),
            ],
        ),
    ]
