# Generated by Django 4.2.16 on 2024-10-19 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackreport',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attackreport',
            name='attack_type',
            field=models.CharField(default='Attack', max_length=6, verbose_name='Attack Type'),
        ),
        migrations.AddField(
            model_name='attackreport',
            name='last_checked_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Checked Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attackreport',
            name='reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='admin_notes',
            field=models.CharField(max_length=200, verbose_name='Defense Coord Notes'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='attack_id',
            field=models.IntegerField(verbose_name='Attack ID'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='attacking_player_name',
            field=models.CharField(max_length=30, verbose_name='Attacker'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='attacking_village_name',
            field=models.CharField(max_length=30, verbose_name='Attacker Village'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='defending_player_name',
            field=models.CharField(max_length=30, verbose_name='Defender'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='defending_village_name',
            field=models.CharField(max_length=30, verbose_name='Defender Village'),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='submitter_notes',
            field=models.CharField(max_length=100, verbose_name='Submitter Notes'),
        ),
    ]
