# Generated by Django 4.2.16 on 2024-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_attackreport_active_flag_attackreport_attack_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackreport',
            name='last_checked_time',
            field=models.DateTimeField(null=True, verbose_name='Last Checked Time'),
        ),
    ]
